name: Deploy Addons to Google Drive

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Flatten and Zip Addons
        run: |
          # Aplanar la estructura de Proyectos para que WoW pueda leerlos
          mkdir flat_addons
          find Proyectos -mindepth 2 -maxdepth 2 -type d -exec cp -r {} flat_addons/ \;
          cd flat_addons
          zip -r ../WoW_Addons_Modificados.zip .
          cd ..

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          filename: "WoW_Addons_Modificados.zip"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
